atlas_connection_string = "mongodb+srv://aarthiselvam:ccwNgJGkDSQR7Ac5@cluster0.s5pbmki.mongodb.net/?retryWrites=true&w=majority"

mysql_connection_string = "mysql+pymysql://remoteuser:DfH87JiAKm5@192.168.1.41:3306/youtube_db"

[mysql]
host="192.168.1.41"
port=3306
user="remoteuser"
password="DfH87JiAKm5"
database="youtube_db"
